# Generated by Django 5.1.4 on 2024-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Customerid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Customername', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('Loan_amount', models.IntegerField()),
            ],
        ),
    ]
